### ISSUE TITLE
Exception occures

### ISSUE THREAD

**Issue by sonalikaratkar** [iplusacademy/report_payments#2]
Hi, I am using Moodle 4.1 version , ihave intallplugin payment report , but while creating custom reports one exception occures.

![image](https://github.com/iplusacademy/report_payments/assets/31913298/b3f213f9-d4b2-4fb7-a850-fba84e7e3847)
![paymnet exception](https://github.com/iplusacademy/report_payments/assets/31913298/9a47c090-230b-446f-89b4-f57bc7e47b1e)

**Comment by iplusacademy** [comment]
THX for the report. 

I will have a look at this problem ASAP.

**Comment by iplusacademy** [comment]
I cannot reproduce this error, so I need some extra info.

Can you enable debugging (site administration / development/ debugging / Debug level : Developer & display debug messages checked) and revisit the page that was throwing the general exception? With debugging enabled some extra info should be shown.

Which payment gateways are you using and did you configure at least 1 payment gateway?

Can you provide me all info about:

- PHP version
- Moodle version
- Database type 
- Database version
- Operating System
- Apache version

**Comment by sonalikaratkar** [comment]
Thanks iplusacademy team  for immediate action.  refer below details

Debug info


***@***.***
•             PHP version :  7.4.29
•             Moodle version: 4.0
•             Database type : mariadb , ( we  using SQLyog for front screen)
•             Database version : (5.5.5-10.4.24-MariaDB)
•             Operating System:  Windows
•             Apache version:  Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29


Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

**Comment by sonalikaratkar** [comment]
Using paypal, inbuilt moodle  payment getway

Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

From: Sonali Karatkar
Sent: Wednesday, May 31, 2023 8:48 AM
To: iplusacademy/report_payments ***@***.***>; iplusacademy/report_payments ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [iplusacademy/report_payments] Exception occures (Issue #2)

Thanks iplusacademy team  for immediate action.  refer below details

Debug info


***@***.***
•             PHP version :  7.4.29
•             Moodle version: 4.0
•             Database type : mariadb , ( we  using SQLyog for front screen)
•             Database version : (5.5.5-10.4.24-MariaDB)
•             Operating System:  Windows
•             Apache version:  Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29


Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

**Comment by sonalikaratkar** [comment]
Dear Team,

Any update. We need to send report to management.

Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

From: Sonali Karatkar
Sent: Wednesday, May 31, 2023 8:49 AM
To: iplusacademy/report_payments ***@***.***>; iplusacademy/report_payments ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [iplusacademy/report_payments] Exception occures (Issue #2)

Using paypal, inbuilt moodle  payment getway

Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

From: Sonali Karatkar
Sent: Wednesday, May 31, 2023 8:48 AM
To: iplusacademy/report_payments ***@***.******@***.***>>; iplusacademy/report_payments ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [iplusacademy/report_payments] Exception occures (Issue #2)

Thanks iplusacademy team  for immediate action.  refer below details

Debug info


***@***.***
•             PHP version :  7.4.29
•             Moodle version: 4.0
•             Database type : mariadb , ( we  using SQLyog for front screen)
•             Database version : (5.5.5-10.4.24-MariaDB)
•             Operating System:  Windows
•             Apache version:  Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29


Thanks & Regards
Sonali Karatkar ,
PHP Programmer, SIS,
Symbiosis Centre for Distance Learning,
Extn.: 020 - 66211111 – 1131
Email:   ***@***.******@***.***>

**Comment by sonalikaratkar** [comment]
![paymentreport](https://github.com/iplusacademy/report_payments/assets/31913298/47618d03-cb5e-491b-b3d4-0668c1824b7f)
•             PHP version :  7.4.29
•             Moodle version: 4.0 
•             Database type : mariadb , ( we  using SQLyog for front screen) 
•             Database version : (5.5.5-10.4.24-MariaDB)
•             Operating System:  Windows 
•             Apache version:  Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/7.4.29
Using paypal, inbuilt moodle  payment getway

**Comment by sonalikaratkar** [comment]
PELase reply asap

**Comment by ewallah** [comment]
For some reason MDL-74364 was never integrated into MOODLE_400_STABLE, as a result the error message is shown,

I will completely remove the MOODLE_400_STABLE support for this plugin.
